### ISSUE TITLE
non-english comments

### ISSUE THREAD

**Issue by Alexey-T** [jdelauney/TGIFViewer#2]
please rename them to En comments. ppl must get idea of comments.

**Comment by jdelauney** [comment]
What's PPL ?

**Comment by jdelauney** [comment]
It's a lot of work and my english is too basic. Perhaps i'll do 2 version one in french and one for english users. I'll only translate interface comments with google translate

It's like us the poor french users or others users wich english is not a natural langage. 
You are english and do you think of us too when you write code ? not necessarily. How many time i use google translate when i don't understand. It's no easy for us too.

I will make effort as much as possible
But you will agree that when you code it's easier to write the comments in your mother tongue rather than another to find your way around.
Put yourself in my place and if it was the opposite and you should write in French, it would be more difficult for you especially if you do not master this language correctly, right?

**Comment by Alexey-T** [comment]
Ppl =people.

**Comment by Alexey-T** [comment]
i'm from Russia. maybe you can write
//Fr comment
//En comment
as 2 lines?

**Comment by jdelauney** [comment]
Yes is what i thinked and what i beginning to  do ;) notes i've translated fr message thrue po file too
